token_map = {
    '+': {'ADD': 1},
    '-': {'SUB': 2},
    '*': {'MULT': 3},
    '/': {'DIV': 4},
    '%': {'MOD': 5},
    '||': {'OR': 6},
    '&&': {'AND': 7},
    '!': {'NOT': 8},
    '==': {'EQL': 9},
    '!=': {'DIF': 10},
    '>': {'GT': 11},
    '>=': {'GET': 12},
    '<': {'LT': 13},
    '<=': {'LET': 14},
    '=': {'ASSG': 15},
    '+=': {'INC': 16},
    '-=': {'DEC': 17},
    '*=': {'ASMU': 18},
    '%=': {'ASMD': 19},
    'int': {'KINT': 20},
    'float': {'KFLT': 21},
    'string': {'KSTR': 22},
    'for': {'FOR': 23},
    'while': {'WHL': 24},
    'break': {'BRK': 25},
    'continue': {'CTN': 26},
    'if': {'IF': 27},
    'else': {'ELSE': 28},
    'return': {'RTN': 29},
    'system': {'SYS': 30},
    'out': {'OUT': 31},
    'print': {'PRT': 32},
    'in': {'IN': 33},
    'scan': {'SCAN': 34},
    ';': {'SMCL': 35},
    ',': {'CLN': 36},
    '{': {'LBRC': 37},
    '}': {'RBRC': 38},
    '(': {'LPAR': 39},
    ')': {'RPAR': 40},
    '.': {'PNT': 41},
    'STR': 42,
    'INT': 43,
    'OCT': 44,
    'HEX': 45,
    'FLT': 46,
    'IDEN': 47,
    '/=': {'ASDV': 48},
}

